library(shiny)
shinyUI(pageWithSidebar(
    headerPanel("Health of the Nation"),
    sidebarPanel(
        selectInput("feature", "Choose a Feature", 
                    choices=c("systolic",
                              "diastolic",
                              "bmi",
                              "weight",
                              "height",
                              "energy",
                              "protein",
                              "carbs",
                              "fibre",
                              "fat_total",
                              "fat_saturated",
                              "cholesterol",
                              "calcium",
                              "sodium",
                              "potassium",
                              "caffeine"),
                    selected = "bmi", width = NULL, size = NULL), 
        p("Use the above dropdown menu to select some particular health ", 
          "indicator"),
        h3("Blood Pressure Measurements"),
        HTML("<li>Systolic",
          "<li>Diastolic"), 
        h3("Body Measurements"),
        HTML("<li>BMI: Body Mass Index",
             "<li>Height",
             "<li>Weight"),
        h3("Daily Dietary/Nutrient Intake"),
        HTML("<li>Energy",
             "<li>Protein",
             "<li>Total Carbohydrates",
             "<li>Fibre",
             "<li>Total Fat",
             "<li>Saturated Fat",
             "<li>Cholesterol",
             "<li>Calcium",
             "<li>Sodium",
             "<li>Potassium",
             "<li>Caffeine Consumtion")
    ),
    mainPanel(
        plotOutput("timelinePlot"),
        plotOutput("densityPlot")
    )
))